### ISSUE TITLE
Verify Transaction 

### ISSUE THREAD

**Issue by hamidhaghdoost** [Plisio/php-lib#1]
It seems that the Plisio's back-end redirects user to the `success_url` with a `GET` request when the transaction is successful. 

How to verify that transaction was really successful and the url is not entered manually?

**Comment by plisdeveloper** [comment]
> It seems that the Plisio's back-end redirects user to the `success_url` with a `GET` request when the transaction is successful.
> 
> How to verify that transaction was really successful and the url is not entered manually?

When creating an invoice, you can specify what parameters to put in the "success_url", for example, it can be some service information about the order, which the user cannot know and which will serve as verification information. You can also specify in "success_url" a page that displays the current status of the order, not "Success" even if the order is still being processed.
All order service information, thanks to which the order status is updated, is passed to "callback_url" and contains a special key - "verify_hash", which can be verified by this function https://plisio.net/documentation/endpoints/create-an-invoice#:~:text=Callback%20data%20PHP%20verification%20example%3A.
and if the function returns "true", it means that the callback was not forged, but sent by our service.

**Comment by Plisio** [comment]
Hello,

There was mistake in README. Please use **success_callback_url** param to get success callback. Here you can find more options: https://plisio.net/documentation/endpoints/create-an-invoice (List of all supported request fields).  Also you can get successfully paid invoises with **callback_url** under **data.status** with comparing value

```

$complete = in_array($status, ['completed', 'mismatch']);
```
Where is:
completed - paid in full
mismatch - overpaid
